language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-onsenui-phonegap' ]; then cd .. && eval "mv $currentfolder generator-onsenui-phonegap" && cd generator-onsenui-phonegap; fi

